### ISSUE TITLE
Зачем второй цикл? Считать бонус нужно было с каждой продажи.

### ISSUE THREAD

**Issue by coursar** [taxa222/ArrayServiceBonus#2]
https://github.com/taxa222/NpsServiceBonus/blob/f01c861914ae2e1cee85e693d965218cdcf56e43/src/main/java/ru/itpark/NpsServiceBonus.java#L11-L23

**Comment by taxa222** [comment]
@coursar пофиксил в f635a710857b1a8930bb1a97b00fc67c2753bc05

**Comment by coursar** [comment]
Если фиксите, то закрывайте issue

Если фиксите исправлениями кода, то в сообщении коммита указывайте "fixed #2"
