### ISSUE TITLE
Логика начисления бонуса

### ISSUE THREAD

**Issue by coursar** [taxa222/ArrayServiceBonus#6]
https://github.com/taxa222/ArrayServiceBonus/blob/2ea36aceee214a3ed7aa55eed45d0f9b049f5de0/src/main/java/ru/itpark/NpsServiceBonus.java#L14-L24

Если конкретная продажа совершена на сумму более 10000, то сумма сверху прибавляется к бонусу.

Вы же в if'е сравниваете "нарастающим" итогом.

Т.е. с  int[] sales = {12_000, 8_000, 15_000,8_000}; бонус должен быть 350 рублей, а не 43000.

**Comment by taxa222** [comment]
исправлено 3fb515074a45618decc9dcd896be0efdc8865af7
